name: starburst-checks

on:
  push:
    branches:
      - release-**
      - master
  pull_request:
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:

defaults:
  run:
    shell: bash --noprofile --norc -euo pipefail {0}


# Cancel previous PR builds.
concurrency:
  # Cancel all workflow runs except latest within a concurrency group. This is achieved by defining a concurrency group for the PR.
  # Non-PR builds have singleton concurrency groups.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  ci-secrets-checks:
    runs-on: [self-hosted, sep-cicd, gha-fleet-nano]
    steps:
      - uses: actions/checkout@v3
      - name: Check for secrets usage in ci
        run: |
          .github/bin/check-ci-secrets.sh .github/workflows/ci.yml
      - name: Check for vars usage in ci
        run: |
          .github/bin/check-ci-vars.sh .github/workflows/ci.yml
